runtime: custom
env: flex

network:
    forwarded_ports:
        - 8080:8080

env_variables:
    APP_URL: $APP_SECRET_APP_URL
    API_URL: $APP_SECRET_API_URL
    API_CLIENT_ID: $APP_SECRET_API_CLIENT_ID
    API_CLIENT_KEY: $APP_SECRET_API_CLIENT_KEY
    SPOTIFY_CLIENT_ID: $APP_SECRET_SPOTIFY_CLIENT_ID
    SPOTIFY_CLIENT_SECRET: $APP_SECRET_SPOTIFY_CLIENT_SECRET
    CALLBACK_URL: $APP_SECRET_CALLBACK_URL
    CLOUDAMQP_URL: $APP_SECRET_CLOUDAMQP_URL
    DEBUG: $APP_SECRET_DEBUG
