version: '3.1'

services:
    main:
        build:
            context: .
            target: development
        volumes:
            - .:/usr/src/app
        ports:
            - 3030:300
        env_file:
            - .env
        depends_on:
            - rabbitmq
    rabbitmq:
        image: 'rabbitmq:3.8-management'
        hostname: 'rabbitmq'
        ports:
            - '5672:5672'
            - '15672:15672'
        restart: 'always'
        environment:
            RABBITMQ_DEFAULT_USER: '${RABBITMQ_DEFAULT_USER}'
            RABBITMQ_DEFAULT_PASS: '${RABBITMQ_DEFAULT_PASS}'
        volumes:
            - './.docker/rabbitmq/data:/var/lib/rabbitmq/mnesia'
