import { z } from 'zod';

export const playlistSchema = z.object({
    id: z.string(),
    spotify_id: z.string(),
    collaborative: z.boolean(),
    description: z.string(),
    external_url: z.string(),
    href: z.string(),
    name: z.string(),
    userId: z.string(),
    public: z.boolean(),
    snapshot_id: z.string(),
    uri: z.string(),
    active: z.boolean(),
    allowed_userIds: z.array(z.string()),
    images: z.array(z.string()),
    createdAt: z.string(),
    updatedAt: z.string(),
    owner: z.object({
        id: z.string(),
        spotify_id: z.string(),
        country: z.string(),
        display_name: z.string(),
        email: z.string(),
        external_url: z.string(),
        followers: z.number(),
        href: z.string(),
        images: z.array(z.string()),
        product: z.string(),
        type: z.string(),
        uri: z.string(),
        accessToken: z.string(),
        refreshToken: z.string(),
        expiresAt: z.string(),
        createdAt: z.string(),
        updatedAt: z.string(),
    }),
});

export const playlistsSchema = z.array(playlistSchema);
